services:
  - type: web
    name: two77pawan
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /engineering
        destination: /engineering/index.html
      - type: rewrite
        source: /engineering/*
        destination: /index.html
      - type: rewrite
        source: /projects/*
        destination: /index.html
